{% extends "index.phtml" %}
{% block header %}{% endblock %} 
{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Lịch sử yêu cầu deposite</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="<?php echo site_url() ?>">Home</a></li>
          <li class="breadcrumb-item active">Lịch sử giao dịch cashout</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<section class="content">
  <div class="container-fluid">
<table>

<div class="row">
<div class="col-md-12 col-xs-12">
  <div class="filters">
     <form method="post" action="">
       <div class="row">
         <div class="col-md-4 col-xs-12">
            <div class="form-group">
               <label for="xxx">Họ và tên</label>
               <input type="text" name="fullname_user" class="form-control" value="" />
            </div>
            <div class="form-group">
               <label for="xxx">Email</label>
               <input type="text" name="email_user" class="form-control" value="" />
            </div>
            
         </div>
         <div class="col-md-4 col-xs-12">
           <div class="form-group">
               <label for="xxx">Phone</label>
               <input type="text" name="phone_user" class="form-control" value="" />
            </div>
            <div class="form-group">
               <label for="xxx">Role</label>
               <input type="text" name="role_user" class="form-control" value="" />
            </div>
         </div>
         <div class="col-md-4 col-xs-12">
           
         </div>
       </div>
     </form>
  </div>
  <!--  -->
  <div class="box">
    <div class="box-header"><h3 class="box-title">Danh sách</h3></div>
    <!-- /.box-header -->
    <div style="display: flex;flex-direction: row">
       <div class="item-box">
          Check All <input type="checkbox" class="check_all" /> <button class="btn btn-info btn-delete-all">Delete All</button>
       </div>
       <div class="item-box" style="margin-left: 32px;">
           <?php
            if($total){
               for ($i=1;$i<=$total;$i++) {
                 echo '<a href="'.site_url("user/index/?page=".$i).'" class="btn btn-xs btn-primary">'.$i.'</a>';
               }
            }
           ?>
       </div>
    </div>
    <div class="box-body">
        
      <table id="dataTable" class='table table-bordered table-striped'>
        <thead>
        <tr>
          <th>STT</th>
          <th>Transaction</th>
          <th>From user</th>
          <th>Type</th>
          <th>Money</th>
          <th>Wallet</th>
          <th>Note</th>
          <th>Method</th>
          <th>status System</th>
          <th>status API</th>
          <th>Date</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
          <?php foreach($users as $key => $val){
            $val->log = str_replace("|", "<br />", $val->log);
            $parent = isset($val->parent)&&$val->parent?json_decode($val->parent):$val->parent;
          ?>
          <tr data-id="<?php echo $val->id_; ?>">
            <td><?php echo ($key+1); ?> <input type="checkbox" class="check_item"  name="ids[]" value="<?php echo $val->id_; ?>" /></td>
            <td>#<?php echo $val->id_; ?> <br/>
            <button class="btn btn-danger btn-sm btn-delete-wallet" data-idUser='<?php echo $val->id_;?>'><i class="fa fa-times"></i></button>
          </td>
          <td width="300">
              <?php
                $from  = $val->from_user;
                if($from){
                  $from  = json_decode($from);
                ?>
                  <?php echo empty($from->fullname_user) ? 'Chưa cập nhật.' : $from->fullname_user; ?> <br />
                  <a href="<?php echo site_url("user/profile/{$from->id_user}"); ?>" class='btn btn-primary btn-sm'><i class="fa fa-eye"></i></a>
                  <button class="btn btn-danger btn-sm btn-delete" data-idUser='<?php echo $from->id_user;?>'><i class="fa fa-times"></i></button>
                  <a href="<?php echo site_url("user/edit/{$from->id_user}"); ?>" class='btn btn-primary btn-sm'><i class="fas fa-pencil-alt"></i></a>
                <?php 
                }
              ?>
            </td>
           
            <th><?php echo $val->type; ?> </th>
            <th><?php echo $val->amount_usd; ?> </th>
            <td><?php echo $val->to_wallet; ?></td>
            <td>
              <?php echo $val->ref; ?> <br/>
              <?php echo $val->note; ?>
            </td>
            <td>
                <?php  echo $val->method; ?> <br/>
            </td>
            <td><?php
               $info = $info?json_decode($val->detail_transaction):null;
               print_r($info);
               if($info && isset($info->status_text) && in_array($info->status_text,array("Pending","Complete"))){
                 echo 'API check sent but not confirm delay.<br/>';
               }


             echo $val->status; ?></td>
            <td><?php echo $val->status_api; ?></td>
            <td><?php echo $val->created_date; ?></td>
            <td  width="300">
              <button type="button" class="btn btn-info btn-sm btn-approve">Approve</button>
              <button type="button" class="btn btn-danger btn-sm btn-reject">Reject</button>
              <button type="button" class="btn btn-warning btn-sm btn-delete">Refund</button>
            </td>
          </tr>
        <?php } ?>
        </tbody>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>
</div></table></div></section>


{% endblock %}

{% block footer %}  
<script src="/~admin/assets/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/~admin/assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>      
<script type="text/javascript">
$(document).ready(function(){
  var dataTable = $('#dataTable').DataTable();


  $(document).on("click",'.btn-delete-all',function(){
      if(confirm('Bạn chắc chắn xoá các tài khoản này không?')){
        var ids = [];
        var trs = [];
          $('#dataTable').find(".check_item:checked").each(function(i,v){
            ids.push(this.value);
            trs.push($(this).closest("tr"));
          });
          $.ajax({
            type: "POST",
            url: "<?php echo site_url("user/deleteall/") ?>",
            async: true,
            data: {id_user:ids},
            success: function(res) {
               try{
                res = JSON.parse(res);
               }catch(ex){

               }

               if(typeof res =="object"){
                 if(res.code){
              
                  showMessageBar(res.message);
                  $.each(trs,function(i,v){
                      v.remove();
                  });
                 }else{
                  alert(res.error);
                 }
               }else{
                alert(res);
               }

            }
        });

      }
  });

  $(document).on("click",'.check_all',function(){
      $('#dataTable').find(".check_item").each(function(i,v){
        this.checked = !this.checked;
      });
  });


  $(document).on("click",".btn-approve",function(){
    var tr =$(this).closest("tr");
    var UID = tr.data('id');
    if(confirm('Bạn chắc chắn muốn thanh toán không?')){
      $.ajax({
          type: "POST",
          url: "<?php echo site_url_ajax("wallet/acceptpayment/approve/") ?>"+UID,
          async: true,
          data: {},
          success: function(res) {
             try{
              res = JSON.parse(res);
             }catch(ex){

             }

             if(typeof res =="object"){
               if(res.code){
                tr.remove();
                showMessageBar(res.message);
                dataTable.fnDraw();
                dataTable.ajax.reload();
               }else{
                showMessageBar(res.error,"warning");
               }
             }else{
              alert(res);
             }

          }
      });

    }
  });

  $(document).on("click",".btn-refund",function(){
    var tr =$(this).closest("tr");
    var UID = tr.data('id');
    if(confirm('Bạn chắc chắn muốn trả lại thanh toán không?')){
      $.ajax({
          type: "POST",
          url: "<?php echo site_url_ajax("wallet/acceptpayment/refund/") ?>"+UID,
          async: true,
          data: {},
          success: function(res) {
             try{
              res = JSON.parse(res);
             }catch(ex){

             }

             if(typeof res =="object"){
               if(res.code){
                tr.remove();
                showMessageBar(res.message);
                dataTable.fnDraw();
                dataTable.ajax.reload();
               }else{
                showMessageBar(res.error,"warning");
               }
             }else{
              alert(res);
             }

          }
      });

    }
  });

  $(document).on("click",".btn-reject",function(){
    var tr =$(this).closest("tr");
    var UID = tr.data('id');
    if(confirm('Bạn chắc chắn muốn trả lại thanh toán không?')){
      $.ajax({
          type: "POST",
          url: "<?php echo site_url_ajax("wallet/acceptpayment/reject/") ?>"+UID,
          async: true,
          data: {},
          success: function(res) {
             try{
              res = JSON.parse(res);
             }catch(ex){

             }

             if(typeof res =="object"){
               if(res.code){
                tr.remove();
                showMessageBar(res.message);
                dataTable.fnDraw();
                dataTable.ajax.reload();
               }else{
                showMessageBar(res.error,"warning");
               }
             }else{
              alert(res);
             }

          }
      });

    }
  });

  $(document).on("click","button.btn-delete",function(){
    var tr =$(this).closest("tr");
    var UID = tr.data('id');
    if(confirm('Bạn chắc chắn muốn xoá không?')){
      $.ajax({
          type: "POST",
          url: "<?php echo site_url("user/delete/") ?>"+UID,
          async: true,
          data: {},
          success: function(res) {
             try{
              res = JSON.parse(res);
             }catch(ex){

             }

             if(typeof res =="object"){
               if(res.code){
                tr.remove();
                showMessageBar(res.message);
                dataTable.fnDraw();
                dataTable.ajax.reload();
               }else{
                showMessageBar(res.error,"warning");
               }
             }else{
              alert(res);
             }

          }
      });

    }
  });

});
</script>
</script>
{% endblock %}