{% extends "index.phtml" %}
{% block header %}{% endblock %} 
{% block content %}


<h1>Tất cả tài khoản nhân viên</h1>
<ol class="breadcrumb">
  <li><a href="{{ url('/user') }}"><i class="fa fa-dashboard"></i>Home</a></li>
</ol>

<div class="row">
  <div class="col-xs-12">
  <a class='btn btn-sm btn-primary' href='{{ url("user/staffAdd") }}' style='margin-bottom:10px;'>Thêm tài khoản</a>

    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Danh sách tài khoản nhân viên</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
      

        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>Code</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Người giới thiệu</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody>
          {% for item in page %}
          <?php
              $who = $item->getReferer();
              $url = site_url('user/profile/'.$item->id_user);
          ?>
            <tr>
              <td><a href='<?php echo $url; ?>' target='_blank'>{{item.barcode|e}}<br/>{{item.username_user|e}}</a></td>
              <td>{{item.phone_user|e}}</td>
              <td>{{item.address_user}}</td>
              <td><?php echo $who?"<a href='".site_url('user/profile/'.$who->id_user)."' target='_blank'>{$who->username_user}</a>":""; ?></td>
              <td>
                <button id='deleteAccount' class="btn btn-danger btn-xs" data-id='{{item.id_user}}'>x</button>
                <!-- <a class='btn btn-primary btn-xs' href='{{ url("user/editStaff/")}}{{item.id_user}}'>+</a> -->
              </td>
            </tr>
          {% endfor  %}

          </tfoot>
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

{% endblock %}
{% block footer %}  

<script src="/~admin/assets/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/~admin/assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>      
<!-- <script src="/~admin/assets/bower_components/ckeditor/ckeditor.js"></script> -->
<script type="text/javascript">
$(function () {$('#example1').DataTable();});
$(document).ready(function () {
    $('button#deleteAccount').click(function () {
        if (confirm('Bạn chắc chắn muốn xoá ?')) {
            var ID = $(this).attr('data-id');

            $.post("<?php echo site_url('user/deleteStaff'); ?>/"+ID, function(status){
              alert(status);
            });

            

        } else {

        }
    });
});
</script>
{% endblock %}

