{% extends "index.phtml" %}
{% block header %}{% endblock %} 
{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Danh sách tài khoản chưa active</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="<?php echo site_url() ?>">Home</a></li>
          <li class="breadcrumb-item active">Chưa active</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<section class="content">
  <div class="container-fluid">
<table>

<div class="row">
<div class="col-xs-12">

  <div class="box">
    <div class="box-header"><h3 class="box-title"></h3></div>
    <!-- /.box-header -->
    
    <div class="box-body">

      <table id="dataTable" class='table table-bordered table-striped'>
        <thead>
        <tr>
          <th>STT</th>
          <th>Barcode</th>
          <th>Tên đăng nhập</th>
          <th>Email</th>
          <th>Số điện thoại</th>
          <th>Quyền</th>
          <th>IP</th>
          <th>Status</th>
          <th>Date</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($users as $key => $val): ?>
          <tr data-id="<?php echo $val->id_user; ?>">
            <td>
              <?php echo $key; ?>
            </td>
            <td><?php echo empty($val->barcode) ? 'Chưa cập nhật.' : $val->barcode; ?><br />
              <a href="profile/<?php echo $val->id_user; ?>" class='btn btn-primary btn-sm'><i class="fa fa-eye"></i></a>
              <button class="btn btn-danger btn-sm btn-delete" data-idUser='<?php echo $val->id_user;?>'><i class="fa fa-times"></i></button>
              <a href="edit/<?php echo $val->id_user; ?>" class='btn btn-primary btn-sm'><i class="fas fa-pencil-alt"></i></a>
            </td>
            <td><?php echo $val->username_user; ?></td>
            <td><?php echo $val->email_user; ?></td>
            <td><?php echo $val->phone_user; ?></td>
            <td><?php echo $val->role_user; ?></td>
            <td><?php echo $val->ip; ?></td>
            <td><button type="button" class="btn btn-sm btn-primary btn-active">Active?</button></td>
            <td class='td-row'>
              <?php echo $val->created_date; ?>
            </td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>
</div></table></div></section>


{% endblock %}

{% block footer %}  
<script src="/~admin/assets/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/~admin/assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>      
<script type="text/javascript">
$(document).ready(function(){
  var dataTable = $('#dataTable').DataTable();
  $(document).on("click",'.btn-active',function(){
    var tr =$(this).closest("tr");
    var UID = tr.data('id');
    if(confirm('Bạn chắc chắn Active tài khoản này không?')){

        $.ajax({
          type: "POST",
          url: "<?php echo site_url("user/active/") ?>",
          async: true,
          data: {id_user:UID},
          success: function(res) {
             try{
              res = JSON.parse(res);
             }catch(ex){

             }

             if(typeof res =="object"){
               if(res.code){
                tr.remove();
                showMessageBar(res.message);
                dataTable.fnDraw();
                dataTable.ajax.reload();
               }else{
                alert(res.error);
               }
             }else{
              alert(res);
             }

          }
      });

    }
  });

  $(document).on("click","button.btn-delete",function(){
    var tr =$(this).closest("tr");
    var UID = tr.data('id');
    if(confirm('Bạn chắc chắn muốn xoá không?')){
      $.ajax({
          type: "POST",
          url: "<?php echo site_url("user/delete/") ?>"+UID,
          async: true,
          data: {},
          success: function(res) {
             try{
              res = JSON.parse(res);
             }catch(ex){

             }

             if(typeof res =="object"){
               if(res.code){
                tr.remove();
                showMessageBar(res.message);
                dataTable.fnDraw();
                dataTable.ajax.reload();
               }else{
                alert(res.error);
               }
             }else{
              alert(res);
             }

          }
      });

    }
  });

});
</script>
{% endblock %}