{% extends "index.phtml" %}
{% block header %}{% endblock %} 
{% block content %}
<h1>Sửa Tài Khoản Thành Viên</h1>

<?php

  if(!isset($user_data) && empty($user_data)){
    $this->response->redirect();
  }

 ?>

<ol class="breadcrumb">
  <li><a href="{{url()}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="{{url('user/customer')}}">Quản trị viên</a></li>
</ol>

<form method='POST' action="{{ url('user/editCustomer') }}/">
  
 <div class="row">
  <div class="col-xs-12">
    <div class="box">
      
      <div class="box-body">  
        <div class="form-group">
            <label for="fullname_user" class="col-sm-10 control-label">Họ và tên</label>
            <div class="col-sm-10">
              <input id='fullname_user' type="text" class="form-control required" minlength="6" name="fullname_user" required value='<?php echo $user_data->fullname_user; ?>'>
            </div>
          </div>
          <div class="form-group">
            <label for="phone_user" class="col-sm-10 control-label">Số điện thoại</label>
            <div class="col-xs-10">
              <input id='phone_user' type="phone" class="form-control required" name="phone_user" required value='<?php echo $user_data->phone_user; ?>'>
            </div>
          </div>
          <div class="form-group">
            <label for="email_user" class="col-sm-10 control-label">Email</label>
            <div class="col-xs-10">
              <input id='email_user' type="email" class="form-control required email" name="email_user" required value='<?php echo $user_data->email_user; ?>'>
            </div>
          </div>
          <div class="form-group">
            <label for="username_user" class="col-sm-10 control-label">Tên đăng nhập</label>
            <div class="col-xs-10">
              <input id='username_user' type="text" class="form-control required" minlength="6" name="username_user" required value='<?php echo $user_data->username_user; ?>'>
            </div>
          </div>


          <div class='form-group'>
            <div class='checkbox'>
              <label>
              <input id='newpassword' type='checkbox' class='form-control'>
              Thay đổi password
            </label>
            </div>
          </div>
          
          <div id='newpassword-active'>
            <div class="form-group">
              <label for="password_user" class="col-sm-10 control-label">Mật khẩu</label>
              <div class="col-xs-10">
                <input id='password_user' type="password" class="form-control required" minlength="6" name="password_user" required>
              </div>
            </div>

            <div class='form-group'>
              <label for='repassword' class="col-sm-10 control-label">Nhập lại mật khẩu</label>
              <div class='col-xs-10'>
              <input id='repassword' type='password' class='form-control required' minlength='6'  name='repassword' required>
              </div>
            </div>
          </div>

          <div class='form-group'>
            <div class='col-xs-10'>
              <label for='address_user' class='col-xs-12 control-label'>Địa chỉ Thành Viên</label>
              <textarea class='form-control' row='4' id='address_user' name='address_user'></textarea>
            </div>
          </div>

           <div class='form-group'>
            <div class='col-xs-10'>
              <label for='info_user' class='col-xs-12 control-label'>Thông tin Thành Viên</label>
              <textarea class='form-control' row='4' id='info_user' name='info_user'></textarea>
            </div>
          </div>
          
          <div class='form-group'>
              <div class='col-xs-10'>
                <input type='submit' class='btn btn-primary btn-sm' value='Thêm mới' style='margin-top:10px;'>
              </div>
          </div>
          
      </div>
    </div>
  </div>
</form>
{% endblock %}

{% block footer %}        
<script type='text/javascript'></script>
{% endblock %}