{% extends "index.phtml" %}
{% block header %}{% endblock %} 
{% block content %}

<h1>Thêm tài khoản nhân viên</h1>

<ol class="breadcrumb">
  <li><a href="{{url('user')}}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="#">Thêm tài khoản</a></li>
</ol>

<form method='POST' action="{{ url('user/staffAdd') }}">
<div class="row">
  <div class="col-xs-9">
    <div class="form-group">
        <label for="fullname_user" class="col-sm-10 control-label">Họ và tên</label>
        <div class="col-sm-10">
          <input id='fullname_user' type="text" class="form-control required" minlength="6" name="fullname_user" required>
        </div>
      </div>
      <div class="form-group">
        <label for="phone_user" class="col-sm-10 control-label">Số điện thoại</label>
        <div class="col-sm-10">
          <input id='phone_user' type="phone" class="form-control required" name="phone_user" required>
        </div>
      </div>
      <div class="form-group">
        <label for="email_user" class="col-sm-10 control-label">Email</label>
        <div class="col-sm-10">
          <input id='email_user' type="email" class="form-control required email" name="email_user" required>
        </div>
      </div>

      <div class="form-group">
        <label for="username_user" class="col-sm-10 control-label">Tên đăng nhập</label>
        <div class="col-sm-10">
          <input id='username_user' type="text" class="form-control required" minlength="6" name="username_user" required>
        </div>
      </div>
     
		<div class='form-group'>
			<label for="address_user" class="col-sm-10 control-label">Địa chỉ</label>
			<div class='col-xs-10'>
			<textarea id='address_user' class='form-control' row='5' name='address_user'></textarea>
			</div>
		</div>

		<div class='form-group'>
			<label for="info_user" class="col-sm-10 control-label">Thông tin</label>
			<div class='col-xs-10'>
			<textarea id='info_user' class='form-control' row='5' name='info_user'></textarea>
			</div>
		</div>

      <div class="form-group">
        <label for="password_user" class="col-sm-10 control-label">Mật khẩu</label>
        <div class="col-sm-10">
          <input id='password_user' type="password" class="form-control required" minlength="6" name="password_user" required>
        </div>
      </div>

      <div class='form-group'>
        <label for='repassword' class="col-sm-10 control-label">Nhập lại mật khẩu</label>
        <div class='col-sm-10'>
        <input id='repassword' type='password' class='form-control required' minlength='6'  name='repassword' required>
        </div>
      </div>
      
      <div class='form-group'>
          <div class='col-sm-10'>
            <input type='submit' class='btn btn-primary btn-sm' value='Thêm mới' style='margin-top:10px;'>
          </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}